<?php
    /**
     * @var \Codilar\Employee\Block\View $block
     */
    $url= $block->getAddUrl();
?>

    <form style="padding: 1rem; margin-top: 1rem; border: 1px solid silver" method="POST" action="<?php echo $block->getAddUrl() ?>" >
        <?php echo $block->getAddUrl() ?>
        <h3>Add new brand</h3>
        <div>
            <div>
                <label>First Name</label>
                <input name="first_name" type="text" />
            </div>
            <div>
                <label>Middle Name</label>
                <input name="middle_name" type="text" />
            </div>
            <div>
                <label>Last Name</label>
                <input name="last_name" type="text" />
            </div>
            <div>
                <label>D.O.B</label>
                <input name="DOB" type="date" placeholder="yyyy-mm-dd" data-date-format="yyyy-mm-dd" />
            </div>

            <div>
                <label>Gender</label>
                <select name="gender">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                </select>
            </div>

            <div>
                <label>Martial Status</label>
                <select name="martial_status">
                    <option value="Unmarried">Unmarried</option>
                    <option value="Married">Married</option>
                </select>
            </div>

            <div>
                <label>Identity Mark </label>
                <input name="identity_mark" type="text" />
            </div>

            <div>
                <label>Blood Group</label>
                <select name="blood_group">
                    <option value="O+">O+</option>
                    <option value="A+">A+</option>
                    <option value="B+">B+</option>
                    <option value="AB+">AB+</option>
                    <option value="O-">O+</option>
                    <option value="A-">A-</option>
                    <option value="B-">B-</option>
                    <option value="AB-">AB-</option>

                </select>
            </div>

            <div>
                <label>Permanent Address</label>
                <textarea name="permenent_address"></textarea>
            </div>

            <label>Currently Working</label>
            <select name="is_active">
                <option value="0">No</option>
                <option value="1">Yes</option>
            </select>

            <div>
                <label>Current Designation</label>
                <input name="current_designation" type="text" />
            </div>
            <div>
                <label>Current Office</label>
                <input name="current_office" type="text" />
            </div>
            <div>
                <label>Current Address</label>
                <textarea name="current_address"> </textarea>
            </div>

            <button>Add</button>
        </div>
    </form>
</div>
