<?php
    /**
     * @var \Codilar\Employee\Block\View $block
     */
    $url= $block->getAddUrl();
?>

<form style="padding: 1rem; margin-top: 1rem; border: 1px solid silver" method="POST" action="<?php echo $block->getUpdatedataUrl() ?>" >
    <?php foreach($block->getSelectedEmployee() as $UpdateDetails): ?>
    <h3>Update Employee</h3>
    <div>
        <div>

            <input name="employeeId" type="hidden" value="<?php echo $UpdateDetails['entity_id']; ?>"/>
        </div>
        <div>
            <label>First Name</label>
            <input name="first_name" type="text" value="<?php echo $UpdateDetails['first_name']; ?>"/>
        </div>
        <div>
            <label>Middle Name</label>
            <input name="middle_name" type="text" value="<?php echo $UpdateDetails['middle_name']; ?>" />
        </div>
        <div>
            <label>Last Name</label>
            <input name="last_name" type="text" value="<?php echo $UpdateDetails['last_name']; ?>"/>
        </div>
        <div>
            <label>D.O.B</label>
            <input name="DOB" type="date" value="<?php echo $UpdateDetails['dob']; ?>" placeholder="yyyy-mm-dd" data-date-format="yyyy-mm-dd" />
        </div>

        <div>
            <label>Gender</label>
            <select name="gender">
                <option value="<?php echo $UpdateDetails['gender']; ?>"><?php echo $UpdateDetails['gender']; ?></option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
            </select>
        </div>

        <div>
            <label>Martial Status</label>
            <select name="martial_status">
                <option value="<?php echo $UpdateDetails['martial_status']; ?>"><?php echo $UpdateDetails['martial_status']; ?></option>
                <option value="Unmarried">Unmarried</option>
                <option value="Married">Married</option>
            </select>
        </div>

        <div>
            <label>Identity Mark </label>
            <input name="identity_mark" type="text" value="<?php echo $UpdateDetails['identity_mark']; ?>"/>
        </div>

        <div>
            <label>Blood Group</label>
            <select name="blood_group">
            <option value="<?php echo $UpdateDetails['blood_group']; ?>"><?php echo $UpdateDetails['blood_group']; ?></option>

                <option value="O+">O+</option>
                <option value="A+">A+</option>
                <option value="B+">B+</option>
                <option value="AB+">AB+</option>
                <option value="O-">O+</option>
                <option value="A-">A-</option>
                <option value="B-">B-</option>
                <option value="AB-">AB-</option>

            </select>
        </div>

        <div>
            <label>Permanent Address</label>
            <textarea name="permanent_address" ><?php echo $UpdateDetails['permanent_address']; ?></textarea>
        </div>

        <label>Currently Working</label>
        <select name="is_active">
            <option value="<?php echo $UpdateDetails['is_active']; ?>"><?php echo $UpdateDetails['currently_working'] ? 'Yes': 'No'; ?></option>
            <option value="0">No</option>
            <option value="1">Yes</option>
        </select>

        <div>
            <label>Current Designation</label>
            <input name="current_designation" type="text" value="<?php echo $UpdateDetails['current_designation']; ?>"/>
        </div>
        <div>
            <label>Current Office</label>
            <input name="current_office" type="text" value="<?php echo $UpdateDetails['current_office']; ?>" />
        </div>
        <div>
            <label>Current Address</label>
            <textarea name="current_address"><?php echo $UpdateDetails['current_address']; ?> </textarea>
        </div>

        <button>Update</button>
    </div>
</form>
<a href=""
</div>
<?php  endforeach; ?>
